const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const SETCURRENTID = "SET-CURRENT_ID";
const TO_ANOTHER_TABLE = "TO_ANOTHER_TABLE";
const SHOW_OPTIONS = "SHOW_OPTIONS";
const HIDDEN_OPTIONS = "HIDDEN_OPTIONS";
const CLEAR_TASKS = "CLEARTASKS";

//in progress Actions
const DONE = "DONE";
const dELETE = "DELETE";
const Start_task = "Start_task";
const CLEAR_TASKS_INPROGRESS = "CLEARTASKSINPROGRESS";

//done Actions
const DELETEITEM = "DELETEITEM";
const CLEAR_TASKS_COMPLETE='CLEAR_TASKS_COMPLETE'
export {
  CLEAR_TASKS_COMPLETE,
  CLEAR_TASKS_INPROGRESS,
  CLEAR_TASKS,
  DELETEITEM,
  Start_task,
  DONE,
  dELETE,
  HIDDEN_OPTIONS,
  SHOW_OPTIONS,
  ADD_TASK,
  DELETE_TASK,
  SETCURRENTID,
  TO_ANOTHER_TABLE,
};
